// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Without this, Prisma tries to use the primary database as its own
    // shadow and every migrate dev fails with "type already exists".
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
